#!/bin/sh
   pid=`ps aux | grep -i Search_String | awk '{print $2}' | head -1`
  echo "$pid"
  
  
  
  
  *******************************************************************************
  other command
  cat filename
  uname -a  show the version of the OS and karnal
  head filename
  tail filename
  
  #generate strace log for ls-la command
  strace -o /tmp/strace.log ls-la
  #using pid run strace for a process
  strace -p pid -o /tmp/strace.log
  #generate the strace for c program using terminal
  strace -o /tmp/strace.log ./filename
  #how to show all process with only pid
  ps -eo pid,cmd
  #how to get only pid of the process based on name
  ps -eo pid, cmd |grep -i process name
  #To show all the details about the all process
  ps -aux
  #to show all the detail about a dedicate process
  ps -aux |grep -i process name
  #want to fatch path of the utility or process
  which process_name
  which ls 
  which strace
  #want to know the 
  #List all shared lib ,  executable or library internally are using or want to debug the binary.
  ldd Mue
  
  #When we have an object file and we don’t have the source code with us and we have to find out the maximum information from the file. To do so objdump plays a very vital role. The main purpose of the objdump command is to help in debugging the object file. It is used for the following listed purposes:

To retrieve archive header
To get the offset of the file
To get the bfdname
To get the demangle
To debug the file
To disassemble the file
To retrieve the file headers
  objdump -p process-name with path
  Ex- objdump -p /opt/McAfee/agent/bin/Mue



  #display all the detail of executable to library
  file executable_name
  
